package Azure::CognitiveNewsSearch::VideoObject;
  use Moose;

  has 'allowHttpsEmbed' => (is => 'ro', isa => 'Bool'  );
  has 'allowMobileEmbed' => (is => 'ro', isa => 'Bool'  );
  has 'embedHtml' => (is => 'ro', isa => 'Str'  );
  has 'isSuperfresh' => (is => 'ro', isa => 'Bool'  );
  has 'motionThumbnailId' => (is => 'ro', isa => 'Str'  );
  has 'motionThumbnailUrl' => (is => 'ro', isa => 'Str'  );
  has 'thumbnail' => (is => 'ro', isa => 'Azure::CognitiveNewsSearch::ImageObject'  );
  has 'videoId' => (is => 'ro', isa => 'Str'  );
  has 'viewCount' => (is => 'ro', isa => 'Int'  );
  has 'contentUrl' => (is => 'ro', isa => 'Str'  );
  has 'height' => (is => 'ro', isa => 'Int'  );
  has 'width' => (is => 'ro', isa => 'Int'  );
  has 'datePublished' => (is => 'ro', isa => 'Str'  );
  has 'provider' => (is => 'ro', isa => 'ArrayRef[Azure::CognitiveNewsSearch::Thing]'  );
  has 'thumbnailUrl' => (is => 'ro', isa => 'Str'  );
  has 'video' => (is => 'ro', isa => 'Azure::CognitiveNewsSearch::VideoObject'  );
  has 'alternateName' => (is => 'ro', isa => 'Str'  );
  has 'bingId' => (is => 'ro', isa => 'Str'  );
  has 'description' => (is => 'ro', isa => 'Str'  );
  has 'image' => (is => 'ro', isa => 'Azure::CognitiveNewsSearch::ImageObject'  );
  has 'name' => (is => 'ro', isa => 'Str'  );
  has 'url' => (is => 'ro', isa => 'Str'  );
  has 'webSearchUrl' => (is => 'ro', isa => 'Str'  );
  has 'id' => (is => 'ro', isa => 'Str'  );
  has '_type' => (is => 'ro', isa => 'Str'  );
1;
