package Azure::ServiceBusManagement::QueueResource;
  use Moose;

  has 'accessedAt' => (is => 'ro', isa => 'Str'  );
  has 'autoDeleteOnIdle' => (is => 'ro', isa => 'Str'  );
  has 'countDetails' => (is => 'ro', isa => 'Any'  );
  has 'createdAt' => (is => 'ro', isa => 'Str'  );
  has 'deadLetteringOnMessageExpiration' => (is => 'ro', isa => 'Bool'  );
  has 'defaultMessageTimeToLive' => (is => 'ro', isa => 'Str'  );
  has 'duplicateDetectionHistoryTimeWindow ' => (is => 'ro', isa => 'Str'  );
  has 'enableBatchedOperations' => (is => 'ro', isa => 'Bool'  );
  has 'enableExpress' => (is => 'ro', isa => 'Bool'  );
  has 'enablePartitioning' => (is => 'ro', isa => 'Bool'  );
  has 'entityAvailabilityStatus ' => (is => 'ro', isa => 'Any'  );
  has 'isAnonymousAccessible' => (is => 'ro', isa => 'Bool'  );
  has 'lockDuration ' => (is => 'ro', isa => 'Str'  );
  has 'maxDeliveryCount ' => (is => 'ro', isa => 'Int'  );
  has 'maxSizeInMegabytes' => (is => 'ro', isa => 'Int'  );
  has 'messageCount ' => (is => 'ro', isa => 'Int'  );
  has 'requiresDuplicateDetection' => (is => 'ro', isa => 'Bool'  );
  has 'requiresSession' => (is => 'ro', isa => 'Bool'  );
  has 'sizeInBytes ' => (is => 'ro', isa => 'Int'  );
  has 'status' => (is => 'ro', isa => 'Any'  );
  has 'supportOrdering' => (is => 'ro', isa => 'Bool'  );
  has 'updatedAt' => (is => 'ro', isa => 'Str'  );
  has 'id' => (is => 'ro', isa => 'Str'  );
  has 'location' => (is => 'ro', isa => 'Str'  );
  has 'name' => (is => 'ro', isa => 'Str'  );
  has 'tags' => (is => 'ro', isa => 'HashRef'  );
  has 'type' => (is => 'ro', isa => 'Str'  );
1;
