package Azure::CognitiveLocalSearch::PostalAddress;
  use Moose;

  has 'addressCountry' => (is => 'ro', isa => 'Str'  );
  has 'addressLocality' => (is => 'ro', isa => 'Str'  );
  has 'addressRegion' => (is => 'ro', isa => 'Str'  );
  has 'addressRegionAbbreviation' => (is => 'ro', isa => 'Str'  );
  has 'addressSubregion' => (is => 'ro', isa => 'Str'  );
  has 'countryIso' => (is => 'ro', isa => 'Str'  );
  has 'formattingRuleId' => (is => 'ro', isa => 'Str'  );
  has 'houseNumber' => (is => 'ro', isa => 'Str'  );
  has 'neighborhood' => (is => 'ro', isa => 'Str'  );
  has 'postOfficeBoxNumber' => (is => 'ro', isa => 'Str'  );
  has 'postalCode' => (is => 'ro', isa => 'Str'  );
  has 'streetAddress' => (is => 'ro', isa => 'Str'  );
  has 'streetName' => (is => 'ro', isa => 'Str'  );
  has 'text' => (is => 'ro', isa => 'Str'  );
  has 'entityPresentationInfo' => (is => 'ro', isa => 'Azure::CognitiveLocalSearch::EntitiesEntityPresentationInfo'  );
  has 'name' => (is => 'ro', isa => 'Str'  );
  has 'url' => (is => 'ro', isa => 'Str'  );
  has 'adaptiveCard' => (is => 'ro', isa => 'Str'  );
  has 'immediateAction' => (is => 'ro', isa => 'ArrayRef[Azure::CognitiveLocalSearch::Action]'  );
  has 'potentialAction' => (is => 'ro', isa => 'ArrayRef[Azure::CognitiveLocalSearch::Action]'  );
  has 'preferredClickthroughUrl' => (is => 'ro', isa => 'Str'  );
  has 'readLink' => (is => 'ro', isa => 'Str'  );
  has 'webSearchUrl' => (is => 'ro', isa => 'Str'  );
  has 'id' => (is => 'ro', isa => 'Str'  );
  has '_type' => (is => 'ro', isa => 'Str'  );
1;
