package Azure::AppServicePlans::Site;
  use Moose;

  has 'id' => (is => 'ro', isa => 'Str'  );
  has 'kind' => (is => 'ro', isa => 'Str'  );
  has 'location' => (is => 'ro', isa => 'Str'  );
  has 'name' => (is => 'ro', isa => 'Str'  );
  has 'tags' => (is => 'ro', isa => 'HashRef'  );
  has 'type' => (is => 'ro', isa => 'Str'  );
  has 'availabilityState' => (is => 'ro', isa => 'Str'  );
  has 'clientAffinityEnabled' => (is => 'ro', isa => 'Bool'  );
  has 'clientCertEnabled' => (is => 'ro', isa => 'Bool'  );
  has 'cloningInfo' => (is => 'ro', isa => 'Azure::AppServicePlans::CloningInfo'  );
  has 'containerSize' => (is => 'ro', isa => 'Int'  );
  has 'dailyMemoryTimeQuota' => (is => 'ro', isa => 'Int'  );
  has 'defaultHostName' => (is => 'ro', isa => 'Str'  );
  has 'enabled' => (is => 'ro', isa => 'Bool'  );
  has 'enabledHostNames' => (is => 'ro', isa => 'ArrayRef[Str]'  );
  has 'gatewaySiteName' => (is => 'ro', isa => 'Str'  );
  has 'hostNameSslStates' => (is => 'ro', isa => 'ArrayRef[Azure::AppServicePlans::HostNameSslState]'  );
  has 'hostNames' => (is => 'ro', isa => 'ArrayRef[Str]'  );
  has 'hostNamesDisabled' => (is => 'ro', isa => 'Bool'  );
  has 'hostingEnvironmentProfile' => (is => 'ro', isa => 'Azure::AppServicePlans::HostingEnvironmentProfile'  );
  has 'isDefaultContainer' => (is => 'ro', isa => 'Bool'  );
  has 'lastModifiedTimeUtc' => (is => 'ro', isa => 'Str'  );
  has 'maxNumberOfWorkers' => (is => 'ro', isa => 'Int'  );
  has 'microService' => (is => 'ro', isa => 'Str'  );
  has 'outboundIpAddresses' => (is => 'ro', isa => 'Str'  );
  has 'premiumAppDeployed' => (is => 'ro', isa => 'Bool'  );
  has 'repositorySiteName' => (is => 'ro', isa => 'Str'  );
  has 'reserved' => (is => 'ro', isa => 'Bool'  );
  has 'resourceGroup' => (is => 'ro', isa => 'Str'  );
  has 'scmSiteAlsoStopped' => (is => 'ro', isa => 'Bool'  );
  has 'serverFarmId' => (is => 'ro', isa => 'Str'  );
  has 'siteConfig' => (is => 'ro', isa => 'Azure::AppServicePlans::SiteConfig'  );
  has 'slotSwapStatus' => (is => 'ro', isa => 'Azure::AppServicePlans::SlotSwapStatus'  );
  has 'state' => (is => 'ro', isa => 'Str'  );
  has 'suspendedTill' => (is => 'ro', isa => 'Str'  );
  has 'targetSwapSlot' => (is => 'ro', isa => 'Str'  );
  has 'trafficManagerHostNames' => (is => 'ro', isa => 'ArrayRef[Str]'  );
  has 'usageState' => (is => 'ro', isa => 'Str'  );
1;
