package Azure::NetworkManagement::VirtualNetworkGatewayConnection;
  use Moose;

  has 'etag' => (is => 'ro', isa => 'Str'  );
  has 'authorizationKey' => (is => 'ro', isa => 'Str'  );
  has 'connectionStatus' => (is => 'ro', isa => 'Str'  );
  has 'connectionType' => (is => 'ro', isa => 'Str'  );
  has 'egressBytesTransferred' => (is => 'ro', isa => 'Int'  );
  has 'enableBgp' => (is => 'ro', isa => 'Bool'  );
  has 'ingressBytesTransferred' => (is => 'ro', isa => 'Int'  );
  has 'localNetworkGateway2' => (is => 'ro', isa => 'Any'  );
  has 'peer' => (is => 'ro', isa => 'Any'  );
  has 'provisioningState' => (is => 'ro', isa => 'Str'  );
  has 'resourceGuid' => (is => 'ro', isa => 'Str'  );
  has 'routingWeight' => (is => 'ro', isa => 'Int'  );
  has 'sharedKey' => (is => 'ro', isa => 'Str'  );
  has 'virtualNetworkGateway1' => (is => 'ro', isa => 'Any'  );
  has 'virtualNetworkGateway2' => (is => 'ro', isa => 'Any'  );
  has 'id' => (is => 'ro', isa => 'Str'  );
  has 'location' => (is => 'ro', isa => 'Str'  );
  has 'name' => (is => 'ro', isa => 'Str'  );
  has 'tags' => (is => 'ro', isa => 'HashRef'  );
  has 'type' => (is => 'ro', isa => 'Str'  );
1;
