package Azure::AzureSQLDatabase::RecommendedIndex;
  use Moose;

  has 'action' => (is => 'ro', isa => 'Str'  );
  has 'columns' => (is => 'ro', isa => 'ArrayRef[Str]'  );
  has 'created' => (is => 'ro', isa => 'Str'  );
  has 'estimatedImpact' => (is => 'ro', isa => 'ArrayRef[Azure::AzureSQLDatabase::OperationImpact]'  );
  has 'includedColumns' => (is => 'ro', isa => 'ArrayRef[Str]'  );
  has 'indexScript' => (is => 'ro', isa => 'Str'  );
  has 'indexType' => (is => 'ro', isa => 'Str'  );
  has 'lastModified' => (is => 'ro', isa => 'Str'  );
  has 'reportedImpact' => (is => 'ro', isa => 'ArrayRef[Azure::AzureSQLDatabase::OperationImpact]'  );
  has 'schema' => (is => 'ro', isa => 'Str'  );
  has 'state' => (is => 'ro', isa => 'Str'  );
  has 'table' => (is => 'ro', isa => 'Str'  );
  has 'id' => (is => 'ro', isa => 'Str'  );
  has 'location' => (is => 'ro', isa => 'Str'  );
  has 'name' => (is => 'ro', isa => 'Str'  );
  has 'tags' => (is => 'ro', isa => 'HashRef'  );
  has 'type' => (is => 'ro', isa => 'Str'  );
1;
