package Azure::Consumption::MarketplaceProperties;
  use Moose;

  has 'accountName' => (is => 'ro', isa => 'Str'  );
  has 'additionalProperties' => (is => 'ro', isa => 'Str'  );
  has 'billingPeriodId' => (is => 'ro', isa => 'Str'  );
  has 'consumedQuantity' => (is => 'ro', isa => 'Num'  );
  has 'consumedService' => (is => 'ro', isa => 'Str'  );
  has 'costCenter' => (is => 'ro', isa => 'Str'  );
  has 'currency' => (is => 'ro', isa => 'Str'  );
  has 'departmentName' => (is => 'ro', isa => 'Str'  );
  has 'instanceId' => (is => 'ro', isa => 'Str'  );
  has 'instanceName' => (is => 'ro', isa => 'Str'  );
  has 'isEstimated' => (is => 'ro', isa => 'Bool'  );
  has 'isRecurringCharge' => (is => 'ro', isa => 'Bool'  );
  has 'meterId' => (is => 'ro', isa => 'Str'  );
  has 'offerName' => (is => 'ro', isa => 'Str'  );
  has 'orderNumber' => (is => 'ro', isa => 'Str'  );
  has 'planName' => (is => 'ro', isa => 'Str'  );
  has 'pretaxCost' => (is => 'ro', isa => 'Num'  );
  has 'publisherName' => (is => 'ro', isa => 'Str'  );
  has 'resourceGroup' => (is => 'ro', isa => 'Str'  );
  has 'resourceRate' => (is => 'ro', isa => 'Num'  );
  has 'subscriptionGuid' => (is => 'ro', isa => 'Str'  );
  has 'subscriptionName' => (is => 'ro', isa => 'Str'  );
  has 'unitOfMeasure' => (is => 'ro', isa => 'Str'  );
  has 'usageEnd' => (is => 'ro', isa => 'Str'  );
  has 'usageStart' => (is => 'ro', isa => 'Str'  );
1;
