package Azure::Consumption::UsageDetailProperties;
  use Moose;

  has 'accountName' => (is => 'ro', isa => 'Str'  );
  has 'additionalProperties' => (is => 'ro', isa => 'Str'  );
  has 'billableQuantity' => (is => 'ro', isa => 'Num'  );
  has 'billingPeriodId' => (is => 'ro', isa => 'Str'  );
  has 'chargesBilledSeparately' => (is => 'ro', isa => 'Bool'  );
  has 'consumedService' => (is => 'ro', isa => 'Str'  );
  has 'costCenter' => (is => 'ro', isa => 'Str'  );
  has 'currency' => (is => 'ro', isa => 'Str'  );
  has 'departmentName' => (is => 'ro', isa => 'Str'  );
  has 'instanceId' => (is => 'ro', isa => 'Str'  );
  has 'instanceLocation' => (is => 'ro', isa => 'Str'  );
  has 'instanceName' => (is => 'ro', isa => 'Str'  );
  has 'invoiceId' => (is => 'ro', isa => 'Str'  );
  has 'isEstimated' => (is => 'ro', isa => 'Bool'  );
  has 'location' => (is => 'ro', isa => 'Str'  );
  has 'meterDetails' => (is => 'ro', isa => 'Azure::Consumption::MeterDetails'  );
  has 'meterId' => (is => 'ro', isa => 'Str'  );
  has 'offerId' => (is => 'ro', isa => 'Str'  );
  has 'partNumber' => (is => 'ro', isa => 'Str'  );
  has 'pretaxCost' => (is => 'ro', isa => 'Num'  );
  has 'product' => (is => 'ro', isa => 'Str'  );
  has 'resourceGuid' => (is => 'ro', isa => 'Str'  );
  has 'subscriptionGuid' => (is => 'ro', isa => 'Str'  );
  has 'subscriptionName' => (is => 'ro', isa => 'Str'  );
  has 'usageEnd' => (is => 'ro', isa => 'Str'  );
  has 'usageQuantity' => (is => 'ro', isa => 'Num'  );
  has 'usageStart' => (is => 'ro', isa => 'Str'  );
1;
