package Azure::LogicAppsManagement::ApiEntity;
  use Moose;

  has 'apiDefinitionUrl' => (is => 'ro', isa => 'Str'  );
  has 'backendService' => (is => 'ro', isa => 'Any'  );
  has 'capabilities' => (is => 'ro', isa => 'ArrayRef[Str]'  );
  has 'changedTime' => (is => 'ro', isa => 'Str'  );
  has 'connectionParameters' => (is => 'ro', isa => 'HashRef'  );
  has 'createdTime' => (is => 'ro', isa => 'Str'  );
  has 'generalInformation' => (is => 'ro', isa => 'Any'  );
  has 'metadata' => (is => 'ro', isa => 'Any'  );
  has 'name' => (is => 'ro', isa => 'Str'  );
  has 'path' => (is => 'ro', isa => 'Str'  );
  has 'policies' => (is => 'ro', isa => 'Any'  );
  has 'protocols' => (is => 'ro', isa => 'ArrayRef[Str]'  );
  has 'runtimeUrls' => (is => 'ro', isa => 'ArrayRef[Str]'  );
  has 'id' => (is => 'ro', isa => 'Str'  );
  has 'kind' => (is => 'ro', isa => 'Str'  );
  has 'location' => (is => 'ro', isa => 'Str'  );
  has 'name' => (is => 'ro', isa => 'Str'  );
  has 'tags' => (is => 'ro', isa => 'HashRef'  );
  has 'type' => (is => 'ro', isa => 'Str'  );
1;
