package Azure::BatchService::CloudPool;
  use Moose;

  has 'allocationState' => (is => 'ro', isa => 'Str'  );
  has 'allocationStateTransitionTime' => (is => 'ro', isa => 'Str'  );
  has 'applicationPackageReferences' => (is => 'ro', isa => 'ArrayRef'  );
  has 'autoScaleEvaluationInterval' => (is => 'ro', isa => 'Str'  );
  has 'autoScaleFormula' => (is => 'ro', isa => 'Str'  );
  has 'autoScaleRun' => (is => 'ro', isa => 'Any'  );
  has 'certificateReferences' => (is => 'ro', isa => 'ArrayRef'  );
  has 'cloudServiceConfiguration' => (is => 'ro', isa => 'Any'  );
  has 'creationTime' => (is => 'ro', isa => 'Str'  );
  has 'currentDedicated' => (is => 'ro', isa => 'Int'  );
  has 'displayName' => (is => 'ro', isa => 'Str'  );
  has 'eTag' => (is => 'ro', isa => 'Str'  );
  has 'enableAutoScale' => (is => 'ro', isa => 'Bool'  );
  has 'enableInterNodeCommunication' => (is => 'ro', isa => 'Bool'  );
  has 'id' => (is => 'ro', isa => 'Str'  );
  has 'lastModified' => (is => 'ro', isa => 'Str'  );
  has 'maxTasksPerNode' => (is => 'ro', isa => 'Int'  );
  has 'metadata' => (is => 'ro', isa => 'ArrayRef'  );
  has 'networkConfiguration' => (is => 'ro', isa => 'Any'  );
  has 'resizeError' => (is => 'ro', isa => 'Any'  );
  has 'resizeTimeout' => (is => 'ro', isa => 'Str'  );
  has 'startTask' => (is => 'ro', isa => 'Any'  );
  has 'state' => (is => 'ro', isa => 'Str'  );
  has 'stateTransitionTime' => (is => 'ro', isa => 'Str'  );
  has 'stats' => (is => 'ro', isa => 'Any'  );
  has 'targetDedicated' => (is => 'ro', isa => 'Int'  );
  has 'taskSchedulingPolicy' => (is => 'ro', isa => 'Any'  );
  has 'url' => (is => 'ro', isa => 'Str'  );
  has 'virtualMachineConfiguration' => (is => 'ro', isa => 'Any'  );
  has 'vmSize' => (is => 'ro', isa => 'Str'  );
1;
