package Azure::BatchService::PoolSpecification;
  use Moose;

  has 'applicationPackageReferences' => (is => 'ro', isa => 'ArrayRef[Azure::BatchService::ApplicationPackageReference]'  );
  has 'autoScaleEvaluationInterval' => (is => 'ro', isa => 'Str'  );
  has 'autoScaleFormula' => (is => 'ro', isa => 'Str'  );
  has 'certificateReferences' => (is => 'ro', isa => 'ArrayRef[Azure::BatchService::CertificateReference]'  );
  has 'cloudServiceConfiguration' => (is => 'ro', isa => 'Azure::BatchService::CloudServiceConfiguration'  );
  has 'displayName' => (is => 'ro', isa => 'Str'  );
  has 'enableAutoScale' => (is => 'ro', isa => 'Bool'  );
  has 'enableInterNodeCommunication' => (is => 'ro', isa => 'Bool'  );
  has 'maxTasksPerNode' => (is => 'ro', isa => 'Int'  );
  has 'metadata' => (is => 'ro', isa => 'ArrayRef[Azure::BatchService::MetadataItem]'  );
  has 'networkConfiguration' => (is => 'ro', isa => 'Azure::BatchService::NetworkConfiguration'  );
  has 'resizeTimeout' => (is => 'ro', isa => 'Str'  );
  has 'startTask' => (is => 'ro', isa => 'Azure::BatchService::StartTask'  );
  has 'targetDedicated' => (is => 'ro', isa => 'Int'  );
  has 'taskSchedulingPolicy' => (is => 'ro', isa => 'Azure::BatchService::TaskSchedulingPolicy'  );
  has 'userAccounts' => (is => 'ro', isa => 'ArrayRef[Azure::BatchService::UserAccount]'  );
  has 'virtualMachineConfiguration' => (is => 'ro', isa => 'Azure::BatchService::VirtualMachineConfiguration'  );
  has 'vmSize' => (is => 'ro', isa => 'Str'  );
1;
