package Azure::BatchAI::GetJobsResult;
  use Moose;

  has id => (is => 'ro', isa => 'Str'  );
  has location => (is => 'ro', isa => 'Str'  );
  has name => (is => 'ro', isa => 'Str'  );
  has tags => (is => 'ro', isa => 'HashRef[Str]'  );
  has type => (is => 'ro', isa => 'Str'  );
  has caffeSettings => (is => 'ro', isa => 'Azure::BatchAI::CaffeSettings'  );
  has chainerSettings => (is => 'ro', isa => 'Azure::BatchAI::ChainerSettings'  );
  has cluster => (is => 'ro', isa => 'Azure::BatchAI::ResourceId'  );
  has cntkSettings => (is => 'ro', isa => 'Azure::BatchAI::CNTKsettings'  );
  has constraints => (is => 'ro', isa => 'Azure::BatchAI::GetJobsResult_constraints'  );
  has containerSettings => (is => 'ro', isa => 'Azure::BatchAI::ContainerSettings'  );
  has creationTime => (is => 'ro', isa => 'Str'  );
  has customToolkitSettings => (is => 'ro', isa => 'Azure::BatchAI::CustomToolkitSettings'  );
  has environmentVariables => (is => 'ro', isa => 'ArrayRef[Azure::BatchAI::EnvironmentSetting]'  );
  has executionInfo => (is => 'ro', isa => 'Azure::BatchAI::GetJobsResult_executionInfo'  );
  has executionState => (is => 'ro', isa => 'Str'  );
  has executionStateTransitionTime => (is => 'ro', isa => 'Str'  );
  has experimentName => (is => 'ro', isa => 'Str'  );
  has inputDirectories => (is => 'ro', isa => 'ArrayRef[Azure::BatchAI::InputDirectory]'  );
  has jobPreparation => (is => 'ro', isa => 'Azure::BatchAI::JobPreparation'  );
  has nodeCount => (is => 'ro', isa => 'Int'  );
  has outputDirectories => (is => 'ro', isa => 'ArrayRef[Azure::BatchAI::OutputDirectory]'  );
  has priority => (is => 'ro', isa => 'Int'  );
  has provisioningState => (is => 'ro', isa => 'Str'  );
  has provisioningStateTransitionTime => (is => 'ro', isa => 'Str'  );
  has stdOutErrPathPrefix => (is => 'ro', isa => 'Str'  );
  has tensorFlowSettings => (is => 'ro', isa => 'Azure::BatchAI::TensorFlowSettings'  );
  has toolType => (is => 'ro', isa => 'Str'  );

1;
