package ServiceFabric::LoadMetricInformation;
  use Moose;

  has 'Action' => (is => 'ro', isa => 'Str'  );
  has 'ActivityThreshold' => (is => 'ro', isa => 'Int'  );
  has 'BalancingThreshold' => (is => 'ro', isa => 'Int'  );
  has 'BufferedCapacity' => (is => 'ro', isa => 'Str'  );
  has 'ClusterCapacity' => (is => 'ro', isa => 'Str'  );
  has 'ClusterLoad' => (is => 'ro', isa => 'Str'  );
  has 'DeviationAfter' => (is => 'ro', isa => 'Int'  );
  has 'DeviationBefore' => (is => 'ro', isa => 'Int'  );
  has 'IsBalancedAfter' => (is => 'ro', isa => 'Any'  );
  has 'IsBalancedBefore' => (is => 'ro', isa => 'Any'  );
  has 'IsClusterCapacityViolation' => (is => 'ro', isa => 'Any'  );
  has 'MaxNodeLoadId' => (is => 'ro', isa => 'HashRef'  );
  has 'MaxNodeLoadValue' => (is => 'ro', isa => 'Str'  );
  has 'MinNodeLoadId' => (is => 'ro', isa => 'HashRef'  );
  has 'MinNodeLoadValue' => (is => 'ro', isa => 'Str'  );
  has 'Name' => (is => 'ro', isa => 'Str'  );
  has 'NodeBufferPercentage' => (is => 'ro', isa => 'Int'  );
  has 'RemainingBufferedCapacity' => (is => 'ro', isa => 'Str'  );
  has 'RemainingUnbufferedCapacity' => (is => 'ro', isa => 'Str'  );
1;
