#!/usr/bin/perl

use v5.10;

use FindBin;
use lib "$FindBin::Bin/../builder-lib";

use strict;
use warnings;
use Azure::SDK::MultiBuilder;

$|=1;

my @files = @ARGV;

die "Usage: $0 file1 [file2 file3]" if (not @files);
my $builder = Azure::SDK::MultiBuilder->new(
  files => \@files,
);
$builder->build;
