package Azure::StorageManagement::ServiceSasParameters;
  use Moose;

  has 'canonicalizedResource' => (is => 'ro', isa => 'Str'  );
  has 'endPk' => (is => 'ro', isa => 'Str'  );
  has 'endRk' => (is => 'ro', isa => 'Str'  );
  has 'keyToSign' => (is => 'ro', isa => 'Str'  );
  has 'rscc' => (is => 'ro', isa => 'Str'  );
  has 'rscd' => (is => 'ro', isa => 'Str'  );
  has 'rsce' => (is => 'ro', isa => 'Str'  );
  has 'rscl' => (is => 'ro', isa => 'Str'  );
  has 'rsct' => (is => 'ro', isa => 'Str'  );
  has 'signedExpiry' => (is => 'ro', isa => 'Str'  );
  has 'signedIdentifier' => (is => 'ro', isa => 'Str'  );
  has 'signedIp' => (is => 'ro', isa => 'Str'  );
  has 'signedPermission' => (is => 'ro', isa => 'Str'  );
  has 'signedProtocol' => (is => 'ro', isa => 'Str'  );
  has 'signedResource' => (is => 'ro', isa => 'Str'  );
  has 'signedStart' => (is => 'ro', isa => 'Str'  );
  has 'startPk' => (is => 'ro', isa => 'Str'  );
  has 'startRk' => (is => 'ro', isa => 'Str'  );
1;
