package Azure::RecoveryServices::HyperVReplicaAzureReplicationDetails;
  use Moose;

  has 'azureVmDiskDetails' => (is => 'ro', isa => 'ArrayRef[Azure::RecoveryServices::AzureVmDiskDetails]'  );
  has 'enableRdpOnTargetOption' => (is => 'ro', isa => 'Str'  );
  has 'encryption' => (is => 'ro', isa => 'Str'  );
  has 'initialReplicationDetails' => (is => 'ro', isa => 'Azure::RecoveryServices::InitialReplicationDetails'  );
  has 'lastReplicatedTime' => (is => 'ro', isa => 'Str'  );
  has 'lastRpoCalculatedTime' => (is => 'ro', isa => 'Str'  );
  has 'licenseType' => (is => 'ro', isa => 'Str'  );
  has 'oSDetails' => (is => 'ro', isa => 'Azure::RecoveryServices::OSDetails'  );
  has 'recoveryAvailabilitySetId' => (is => 'ro', isa => 'Str'  );
  has 'recoveryAzureLogStorageAccountId' => (is => 'ro', isa => 'Str'  );
  has 'recoveryAzureResourceGroupId' => (is => 'ro', isa => 'Str'  );
  has 'recoveryAzureStorageAccount' => (is => 'ro', isa => 'Str'  );
  has 'recoveryAzureVMSize' => (is => 'ro', isa => 'Str'  );
  has 'recoveryAzureVmName' => (is => 'ro', isa => 'Str'  );
  has 'rpoInSeconds' => (is => 'ro', isa => 'Int'  );
  has 'selectedRecoveryAzureNetworkId' => (is => 'ro', isa => 'Str'  );
  has 'selectedSourceNicId' => (is => 'ro', isa => 'Str'  );
  has 'sourceVmCpuCount' => (is => 'ro', isa => 'Int'  );
  has 'sourceVmRamSizeInMB' => (is => 'ro', isa => 'Int'  );
  has 'useManagedDisks' => (is => 'ro', isa => 'Str'  );
  has 'vmId' => (is => 'ro', isa => 'Str'  );
  has 'vmNics' => (is => 'ro', isa => 'ArrayRef[Azure::RecoveryServices::VMNicDetails]'  );
  has 'vmProtectionState' => (is => 'ro', isa => 'Str'  );
  has 'vmProtectionStateDescription' => (is => 'ro', isa => 'Str'  );
  has 'instanceType' => (is => 'ro', isa => 'Str'  );
1;
