package Azure::RecoveryServices::VMwareDetails;
  use Moose;

  has 'agentCount' => (is => 'ro', isa => 'Str'  );
  has 'agentExpiryDate' => (is => 'ro', isa => 'Str'  );
  has 'agentVersion' => (is => 'ro', isa => 'Str'  );
  has 'agentVersionDetails' => (is => 'ro', isa => 'Azure::RecoveryServices::VersionDetails'  );
  has 'availableMemoryInBytes' => (is => 'ro', isa => 'Int'  );
  has 'availableSpaceInBytes' => (is => 'ro', isa => 'Int'  );
  has 'cpuLoad' => (is => 'ro', isa => 'Str'  );
  has 'cpuLoadStatus' => (is => 'ro', isa => 'Str'  );
  has 'csServiceStatus' => (is => 'ro', isa => 'Str'  );
  has 'databaseServerLoad' => (is => 'ro', isa => 'Str'  );
  has 'databaseServerLoadStatus' => (is => 'ro', isa => 'Str'  );
  has 'hostName' => (is => 'ro', isa => 'Str'  );
  has 'ipAddress' => (is => 'ro', isa => 'Str'  );
  has 'lastHeartbeat' => (is => 'ro', isa => 'Str'  );
  has 'masterTargetServers' => (is => 'ro', isa => 'ArrayRef[Azure::RecoveryServices::MasterTargetServer]'  );
  has 'memoryUsageStatus' => (is => 'ro', isa => 'Str'  );
  has 'processServerCount' => (is => 'ro', isa => 'Str'  );
  has 'processServers' => (is => 'ro', isa => 'ArrayRef[Azure::RecoveryServices::ProcessServer]'  );
  has 'protectedServers' => (is => 'ro', isa => 'Str'  );
  has 'psTemplateVersion' => (is => 'ro', isa => 'Str'  );
  has 'replicationPairCount' => (is => 'ro', isa => 'Str'  );
  has 'runAsAccounts' => (is => 'ro', isa => 'ArrayRef[Azure::RecoveryServices::RunAsAccount]'  );
  has 'spaceUsageStatus' => (is => 'ro', isa => 'Str'  );
  has 'sslCertExpiryDate' => (is => 'ro', isa => 'Str'  );
  has 'sslCertExpiryRemainingDays' => (is => 'ro', isa => 'Int'  );
  has 'systemLoad' => (is => 'ro', isa => 'Str'  );
  has 'systemLoadStatus' => (is => 'ro', isa => 'Str'  );
  has 'totalMemoryInBytes' => (is => 'ro', isa => 'Int'  );
  has 'totalSpaceInBytes' => (is => 'ro', isa => 'Int'  );
  has 'versionStatus' => (is => 'ro', isa => 'Str'  );
  has 'webLoad' => (is => 'ro', isa => 'Str'  );
  has 'webLoadStatus' => (is => 'ro', isa => 'Str'  );
  has 'instanceType' => (is => 'ro', isa => 'Str'  );
1;
