package Azure::DevTestLabs::GetResourceVirtualMachineResult;
  use Moose;

  has id => (is => 'ro', isa => 'Str'  );
  has location => (is => 'ro', isa => 'Str'  );
  has name => (is => 'ro', isa => 'Str'  );
  has tags => (is => 'ro', isa => 'HashRef'  );
  has type => (is => 'ro', isa => 'Str'  );
  has artifactDeploymentStatus => (is => 'ro', isa => 'HashRef'  );
  has artifacts => (is => 'ro', isa => 'ArrayRef[Azure::DevTestLabs::ArtifactInstallProperties]'  );
  has computeId => (is => 'ro', isa => 'Str'  );
  has createdByUser => (is => 'ro', isa => 'Str'  );
  has createdByUserId => (is => 'ro', isa => 'Str'  );
  has customImageId => (is => 'ro', isa => 'Str'  );
  has disallowPublicIpAddress => (is => 'ro', isa => 'Bool'  );
  has fqdn => (is => 'ro', isa => 'Str'  );
  has galleryImageReference => (is => 'ro', isa => 'HashRef'  );
  has isAuthenticationWithSshKey => (is => 'ro', isa => 'Bool'  );
  has labSubnetName => (is => 'ro', isa => 'Str'  );
  has labVirtualNetworkId => (is => 'ro', isa => 'Str'  );
  has notes => (is => 'ro', isa => 'Str'  );
  has osType => (is => 'ro', isa => 'Str'  );
  has ownerObjectId => (is => 'ro', isa => 'Str'  );
  has password => (is => 'ro', isa => 'Str'  );
  has provisioningState => (is => 'ro', isa => 'Str'  );
  has size => (is => 'ro', isa => 'Str'  );
  has sshKey => (is => 'ro', isa => 'Str'  );
  has uniqueIdentifier => (is => 'ro', isa => 'Str'  );
  has userName => (is => 'ro', isa => 'Str'  );

1;
