package Azure::DevTestLabs::LabVirtualMachinePropertiesFragment;
  use Moose;

  has 'allowClaim' => (is => 'ro', isa => 'Bool'  );
  has 'applicableSchedule' => (is => 'ro', isa => 'Azure::DevTestLabs::ApplicableScheduleFragment'  );
  has 'artifactDeploymentStatus' => (is => 'ro', isa => 'Azure::DevTestLabs::ArtifactDeploymentStatusPropertiesFragment'  );
  has 'artifacts' => (is => 'ro', isa => 'ArrayRef[Azure::DevTestLabs::ArtifactInstallPropertiesFragment]'  );
  has 'computeVm' => (is => 'ro', isa => 'Azure::DevTestLabs::ComputeVmPropertiesFragment'  );
  has 'createdByUser' => (is => 'ro', isa => 'Str'  );
  has 'createdByUserId' => (is => 'ro', isa => 'Str'  );
  has 'createdDate' => (is => 'ro', isa => 'Str'  );
  has 'customImageId' => (is => 'ro', isa => 'Str'  );
  has 'disallowPublicIpAddress' => (is => 'ro', isa => 'Bool'  );
  has 'environmentId' => (is => 'ro', isa => 'Str'  );
  has 'expirationDate' => (is => 'ro', isa => 'Str'  );
  has 'fqdn' => (is => 'ro', isa => 'Str'  );
  has 'galleryImageReference' => (is => 'ro', isa => 'Azure::DevTestLabs::GalleryImageReferenceFragment'  );
  has 'isAuthenticationWithSshKey' => (is => 'ro', isa => 'Bool'  );
  has 'labSubnetName' => (is => 'ro', isa => 'Str'  );
  has 'labVirtualNetworkId' => (is => 'ro', isa => 'Str'  );
  has 'networkInterface' => (is => 'ro', isa => 'Azure::DevTestLabs::NetworkInterfacePropertiesFragment'  );
  has 'notes' => (is => 'ro', isa => 'Str'  );
  has 'osType' => (is => 'ro', isa => 'Str'  );
  has 'ownerObjectId' => (is => 'ro', isa => 'Str'  );
  has 'ownerUserPrincipalName' => (is => 'ro', isa => 'Str'  );
  has 'password' => (is => 'ro', isa => 'Str'  );
  has 'provisioningState' => (is => 'ro', isa => 'Str'  );
  has 'size' => (is => 'ro', isa => 'Str'  );
  has 'sshKey' => (is => 'ro', isa => 'Str'  );
  has 'storageType' => (is => 'ro', isa => 'Str'  );
  has 'uniqueIdentifier' => (is => 'ro', isa => 'Str'  );
  has 'userName' => (is => 'ro', isa => 'Str'  );
  has 'virtualMachineCreationSource' => (is => 'ro', isa => 'Str'  );
1;
