package Azure::MLWebServicesManagement::WebServiceProperties;
  use Moose;

  has 'assets' => (is => 'ro', isa => 'HashRef'  );
  has 'commitmentPlan' => (is => 'ro', isa => 'Azure::MLWebServicesManagement::CommitmentPlan'  );
  has 'createdOn' => (is => 'ro', isa => 'Str'  );
  has 'description' => (is => 'ro', isa => 'Str'  );
  has 'diagnostics' => (is => 'ro', isa => 'Azure::MLWebServicesManagement::DiagnosticsConfiguration'  );
  has 'exampleRequest' => (is => 'ro', isa => 'Azure::MLWebServicesManagement::ExampleRequest'  );
  has 'exposeSampleData' => (is => 'ro', isa => 'Bool'  );
  has 'input' => (is => 'ro', isa => 'Azure::MLWebServicesManagement::ServiceInputOutputSpecification'  );
  has 'keys' => (is => 'ro', isa => 'Azure::MLWebServicesManagement::WebServiceKeys'  );
  has 'machineLearningWorkspace' => (is => 'ro', isa => 'Azure::MLWebServicesManagement::MachineLearningWorkspace'  );
  has 'modifiedOn' => (is => 'ro', isa => 'Str'  );
  has 'output' => (is => 'ro', isa => 'Azure::MLWebServicesManagement::ServiceInputOutputSpecification'  );
  has 'packageType' => (is => 'ro', isa => 'Str'  );
  has 'parameters' => (is => 'ro', isa => 'HashRef'  );
  has 'provisioningState' => (is => 'ro', isa => 'Str'  );
  has 'readOnly' => (is => 'ro', isa => 'Bool'  );
  has 'realtimeConfiguration' => (is => 'ro', isa => 'Azure::MLWebServicesManagement::RealtimeConfiguration'  );
  has 'storageAccount' => (is => 'ro', isa => 'Azure::MLWebServicesManagement::StorageAccount'  );
  has 'swaggerLocation' => (is => 'ro', isa => 'Str'  );
  has 'title' => (is => 'ro', isa => 'Str'  );
1;
