package Azure::PolicyInsights::PolicyState;
  use Moose;

  has '@odata.context' => (is => 'ro', isa => 'Str'  );
  has '@odata.id' => (is => 'ro', isa => 'Str'  );
  has 'effectiveParameters' => (is => 'ro', isa => 'Str'  );
  has 'isCompliant' => (is => 'ro', isa => 'Bool'  );
  has 'managementGroupIds' => (is => 'ro', isa => 'Str'  );
  has 'policyAssignmentId' => (is => 'ro', isa => 'Str'  );
  has 'policyAssignmentName' => (is => 'ro', isa => 'Str'  );
  has 'policyAssignmentOwner' => (is => 'ro', isa => 'Str'  );
  has 'policyAssignmentParameters' => (is => 'ro', isa => 'Str'  );
  has 'policyAssignmentScope' => (is => 'ro', isa => 'Str'  );
  has 'policyDefinitionAction' => (is => 'ro', isa => 'Str'  );
  has 'policyDefinitionCategory' => (is => 'ro', isa => 'Str'  );
  has 'policyDefinitionId' => (is => 'ro', isa => 'Str'  );
  has 'policyDefinitionName' => (is => 'ro', isa => 'Str'  );
  has 'policyDefinitionReferenceId' => (is => 'ro', isa => 'Str'  );
  has 'policySetDefinitionCategory' => (is => 'ro', isa => 'Str'  );
  has 'policySetDefinitionId' => (is => 'ro', isa => 'Str'  );
  has 'policySetDefinitionName' => (is => 'ro', isa => 'Str'  );
  has 'policySetDefinitionOwner' => (is => 'ro', isa => 'Str'  );
  has 'policySetDefinitionParameters' => (is => 'ro', isa => 'Str'  );
  has 'resourceGroup' => (is => 'ro', isa => 'Str'  );
  has 'resourceId' => (is => 'ro', isa => 'Str'  );
  has 'resourceLocation' => (is => 'ro', isa => 'Str'  );
  has 'resourceTags' => (is => 'ro', isa => 'Str'  );
  has 'resourceType' => (is => 'ro', isa => 'Str'  );
  has 'subscriptionId' => (is => 'ro', isa => 'Str'  );
  has 'timestamp' => (is => 'ro', isa => 'Str'  );
1;
