package Azure::SiteRecoveryManagement::A2AReplicationDetails;
  use Moose;

  has 'agentVersion' => (is => 'ro', isa => 'Str'  );
  has 'fabricObjectId' => (is => 'ro', isa => 'Str'  );
  has 'isReplicationAgentUpdateRequired' => (is => 'ro', isa => 'Bool'  );
  has 'lastHeartbeat' => (is => 'ro', isa => 'Str'  );
  has 'lastRpoCalculatedTime' => (is => 'ro', isa => 'Str'  );
  has 'lifecycleId' => (is => 'ro', isa => 'Str'  );
  has 'managementId' => (is => 'ro', isa => 'Str'  );
  has 'monitoringJobType' => (is => 'ro', isa => 'Str'  );
  has 'monitoringPercentageCompletion' => (is => 'ro', isa => 'Int'  );
  has 'multiVmGroupId' => (is => 'ro', isa => 'Str'  );
  has 'multiVmGroupName' => (is => 'ro', isa => 'Str'  );
  has 'osType' => (is => 'ro', isa => 'Str'  );
  has 'primaryFabricLocation' => (is => 'ro', isa => 'Str'  );
  has 'protectedDisks' => (is => 'ro', isa => 'ArrayRef[Azure::SiteRecoveryManagement::A2AProtectedDiskDetails]'  );
  has 'protectedManagedDisks' => (is => 'ro', isa => 'ArrayRef[Azure::SiteRecoveryManagement::A2AProtectedManagedDiskDetails]'  );
  has 'recoveryAvailabilitySet' => (is => 'ro', isa => 'Str'  );
  has 'recoveryAzureResourceGroupId' => (is => 'ro', isa => 'Str'  );
  has 'recoveryAzureVMName' => (is => 'ro', isa => 'Str'  );
  has 'recoveryAzureVMSize' => (is => 'ro', isa => 'Str'  );
  has 'recoveryCloudService' => (is => 'ro', isa => 'Str'  );
  has 'recoveryFabricLocation' => (is => 'ro', isa => 'Str'  );
  has 'recoveryFabricObjectId' => (is => 'ro', isa => 'Str'  );
  has 'rpoInSeconds' => (is => 'ro', isa => 'Int'  );
  has 'selectedRecoveryAzureNetworkId' => (is => 'ro', isa => 'Str'  );
  has 'testFailoverRecoveryFabricObjectId' => (is => 'ro', isa => 'Str'  );
  has 'vmNics' => (is => 'ro', isa => 'ArrayRef[Azure::SiteRecoveryManagement::VMNicDetails]'  );
  has 'vmProtectionState' => (is => 'ro', isa => 'Str'  );
  has 'vmProtectionStateDescription' => (is => 'ro', isa => 'Str'  );
  has 'vmSyncedConfigDetails' => (is => 'ro', isa => 'Azure::SiteRecoveryManagement::AzureToAzureVmSyncedConfigDetails'  );
  has 'instanceType' => (is => 'ro', isa => 'Str'  );
1;
