package Azure::CognitiveFace::FaceLandmarks;
  use Moose;

  has 'eyeLeftBottom' => (is => 'ro', isa => 'Azure::CognitiveFace::Coordinate'  );
  has 'eyeLeftInner' => (is => 'ro', isa => 'Azure::CognitiveFace::Coordinate'  );
  has 'eyeLeftOuter' => (is => 'ro', isa => 'Azure::CognitiveFace::Coordinate'  );
  has 'eyeLeftTop' => (is => 'ro', isa => 'Azure::CognitiveFace::Coordinate'  );
  has 'eyeRightBottom' => (is => 'ro', isa => 'Azure::CognitiveFace::Coordinate'  );
  has 'eyeRightInner' => (is => 'ro', isa => 'Azure::CognitiveFace::Coordinate'  );
  has 'eyeRightOuter' => (is => 'ro', isa => 'Azure::CognitiveFace::Coordinate'  );
  has 'eyeRightTop' => (is => 'ro', isa => 'Azure::CognitiveFace::Coordinate'  );
  has 'eyebrowLeftInner' => (is => 'ro', isa => 'Azure::CognitiveFace::Coordinate'  );
  has 'eyebrowLeftOuter' => (is => 'ro', isa => 'Azure::CognitiveFace::Coordinate'  );
  has 'eyebrowRightInner' => (is => 'ro', isa => 'Azure::CognitiveFace::Coordinate'  );
  has 'eyebrowRightOuter' => (is => 'ro', isa => 'Azure::CognitiveFace::Coordinate'  );
  has 'mouthLeft' => (is => 'ro', isa => 'Azure::CognitiveFace::Coordinate'  );
  has 'mouthRight' => (is => 'ro', isa => 'Azure::CognitiveFace::Coordinate'  );
  has 'noseLeftAlarOutTip' => (is => 'ro', isa => 'Azure::CognitiveFace::Coordinate'  );
  has 'noseLeftAlarTop' => (is => 'ro', isa => 'Azure::CognitiveFace::Coordinate'  );
  has 'noseRightAlarOutTip' => (is => 'ro', isa => 'Azure::CognitiveFace::Coordinate'  );
  has 'noseRightAlarTop' => (is => 'ro', isa => 'Azure::CognitiveFace::Coordinate'  );
  has 'noseRootLeft' => (is => 'ro', isa => 'Azure::CognitiveFace::Coordinate'  );
  has 'noseRootRight' => (is => 'ro', isa => 'Azure::CognitiveFace::Coordinate'  );
  has 'noseTip' => (is => 'ro', isa => 'Azure::CognitiveFace::Coordinate'  );
  has 'pupilLeft' => (is => 'ro', isa => 'Azure::CognitiveFace::Coordinate'  );
  has 'pupilRight' => (is => 'ro', isa => 'Azure::CognitiveFace::Coordinate'  );
  has 'underLipBottom' => (is => 'ro', isa => 'Azure::CognitiveFace::Coordinate'  );
  has 'underLipTop' => (is => 'ro', isa => 'Azure::CognitiveFace::Coordinate'  );
  has 'upperLipBottom' => (is => 'ro', isa => 'Azure::CognitiveFace::Coordinate'  );
  has 'upperLipTop' => (is => 'ro', isa => 'Azure::CognitiveFace::Coordinate'  );
1;
