package Azure::Web::Site;
  use Moose;

  has 'identity' => (is => 'ro', isa => 'Azure::Web::ManagedServiceIdentity'  );
  has 'id' => (is => 'ro', isa => 'Str'  );
  has 'kind' => (is => 'ro', isa => 'Str'  );
  has 'location' => (is => 'ro', isa => 'Str'  );
  has 'name' => (is => 'ro', isa => 'Str'  );
  has 'tags' => (is => 'ro', isa => 'HashRef[Str]'  );
  has 'type' => (is => 'ro', isa => 'Str'  );
  has 'availabilityState' => (is => 'ro', isa => 'Str'  );
  has 'clientAffinityEnabled' => (is => 'ro', isa => 'Bool'  );
  has 'clientCertEnabled' => (is => 'ro', isa => 'Bool'  );
  has 'cloningInfo' => (is => 'ro', isa => 'Azure::Web::CloningInfo'  );
  has 'containerSize' => (is => 'ro', isa => 'Int'  );
  has 'dailyMemoryTimeQuota' => (is => 'ro', isa => 'Int'  );
  has 'defaultHostName' => (is => 'ro', isa => 'Str'  );
  has 'enabled' => (is => 'ro', isa => 'Bool'  );
  has 'enabledHostNames' => (is => 'ro', isa => 'ArrayRef[Str]'  );
  has 'hostNameSslStates' => (is => 'ro', isa => 'ArrayRef[Azure::Web::HostNameSslState]'  );
  has 'hostNames' => (is => 'ro', isa => 'ArrayRef[Str]'  );
  has 'hostNamesDisabled' => (is => 'ro', isa => 'Bool'  );
  has 'hostingEnvironmentProfile' => (is => 'ro', isa => 'Azure::Web::HostingEnvironmentProfile'  );
  has 'httpsOnly' => (is => 'ro', isa => 'Bool'  );
  has 'hyperV' => (is => 'ro', isa => 'Bool'  );
  has 'isDefaultContainer' => (is => 'ro', isa => 'Bool'  );
  has 'isXenon' => (is => 'ro', isa => 'Bool'  );
  has 'lastModifiedTimeUtc' => (is => 'ro', isa => 'Str'  );
  has 'maxNumberOfWorkers' => (is => 'ro', isa => 'Int'  );
  has 'outboundIpAddresses' => (is => 'ro', isa => 'Str'  );
  has 'possibleOutboundIpAddresses' => (is => 'ro', isa => 'Str'  );
  has 'repositorySiteName' => (is => 'ro', isa => 'Str'  );
  has 'reserved' => (is => 'ro', isa => 'Bool'  );
  has 'resourceGroup' => (is => 'ro', isa => 'Str'  );
  has 'scmSiteAlsoStopped' => (is => 'ro', isa => 'Bool'  );
  has 'serverFarmId' => (is => 'ro', isa => 'Str'  );
  has 'siteConfig' => (is => 'ro', isa => 'Azure::Web::SiteConfig'  );
  has 'slotSwapStatus' => (is => 'ro', isa => 'Azure::Web::SlotSwapStatus'  );
  has 'state' => (is => 'ro', isa => 'Str'  );
  has 'suspendedTill' => (is => 'ro', isa => 'Str'  );
  has 'targetSwapSlot' => (is => 'ro', isa => 'Str'  );
  has 'trafficManagerHostNames' => (is => 'ro', isa => 'ArrayRef[Str]'  );
  has 'usageState' => (is => 'ro', isa => 'Str'  );
1;
