package Azure::ADHybridHealthService::AddsServiceMember;
  use Moose;

  has 'activeAlerts' => (is => 'ro', isa => 'Int'  );
  has 'additionalInformation' => (is => 'ro', isa => 'Str'  );
  has 'addsRoles' => (is => 'ro', isa => 'ArrayRef[Str]'  );
  has 'createdDate' => (is => 'ro', isa => 'Str'  );
  has 'dcTypes' => (is => 'ro', isa => 'ArrayRef[Str]'  );
  has 'dimensions' => (is => 'ro', isa => 'ArrayRef[Azure::ADHybridHealthService::Item]'  );
  has 'disabled' => (is => 'ro', isa => 'Bool'  );
  has 'disabledReason' => (is => 'ro', isa => 'Int'  );
  has 'domainName' => (is => 'ro', isa => 'Str'  );
  has 'gcReachable' => (is => 'ro', isa => 'Bool'  );
  has 'installedQfes' => (is => 'ro', isa => 'ArrayRef[Azure::ADHybridHealthService::Hotfix]'  );
  has 'isAdvertising' => (is => 'ro', isa => 'Bool'  );
  has 'lastDisabled' => (is => 'ro', isa => 'Str'  );
  has 'lastReboot' => (is => 'ro', isa => 'Str'  );
  has 'lastServerReportedMonitoringLevelChange' => (is => 'ro', isa => 'Str'  );
  has 'lastUpdated' => (is => 'ro', isa => 'Str'  );
  has 'machineId' => (is => 'ro', isa => 'Str'  );
  has 'machineName' => (is => 'ro', isa => 'Str'  );
  has 'monitoringConfigurationsComputed' => (is => 'ro', isa => 'ArrayRef[Azure::ADHybridHealthService::Item]'  );
  has 'monitoringConfigurationsCustomized' => (is => 'ro', isa => 'ArrayRef[Azure::ADHybridHealthService::Item]'  );
  has 'osName' => (is => 'ro', isa => 'Str'  );
  has 'osVersion' => (is => 'ro', isa => 'Str'  );
  has 'pdcReachable' => (is => 'ro', isa => 'Bool'  );
  has 'properties' => (is => 'ro', isa => 'ArrayRef[Azure::ADHybridHealthService::Item]'  );
  has 'recommendedQfes' => (is => 'ro', isa => 'ArrayRef[Azure::ADHybridHealthService::Hotfix]'  );
  has 'resolvedAlerts' => (is => 'ro', isa => 'Int'  );
  has 'role' => (is => 'ro', isa => 'Str'  );
  has 'serverReportedMonitoringLevel' => (is => 'ro', isa => 'Str'  );
  has 'serviceId' => (is => 'ro', isa => 'Str'  );
  has 'serviceMemberId' => (is => 'ro', isa => 'Str'  );
  has 'siteName' => (is => 'ro', isa => 'Str'  );
  has 'status' => (is => 'ro', isa => 'Str'  );
  has 'sysvolState' => (is => 'ro', isa => 'Bool'  );
  has 'tenantId' => (is => 'ro', isa => 'Str'  );
1;
