package Azure::ADHybridHealthService::ExportError;
  use Moose;

  has 'aadDisplayName' => (is => 'ro', isa => 'Str'  );
  has 'aadDistringuishedName' => (is => 'ro', isa => 'Str'  );
  has 'aadMail' => (is => 'ro', isa => 'Str'  );
  has 'aadObjectGuid' => (is => 'ro', isa => 'Str'  );
  has 'aadObjectType' => (is => 'ro', isa => 'Str'  );
  has 'aadSourceOfAuthority' => (is => 'ro', isa => 'Str'  );
  has 'aadUserPrincipalName' => (is => 'ro', isa => 'Str'  );
  has 'adDisplayName' => (is => 'ro', isa => 'Str'  );
  has 'adDistinguishedName' => (is => 'ro', isa => 'Str'  );
  has 'adMail' => (is => 'ro', isa => 'Str'  );
  has 'adObjectGuid' => (is => 'ro', isa => 'Str'  );
  has 'adObjectType' => (is => 'ro', isa => 'Str'  );
  has 'adSourceAnchor' => (is => 'ro', isa => 'Str'  );
  has 'adSourceOfAuthority' => (is => 'ro', isa => 'Str'  );
  has 'adUserPrincipalName' => (is => 'ro', isa => 'Str'  );
  has 'attributeMultiValue' => (is => 'ro', isa => 'Bool'  );
  has 'attributeName' => (is => 'ro', isa => 'Str'  );
  has 'attributeValue' => (is => 'ro', isa => 'Str'  );
  has 'cloudAnchor' => (is => 'ro', isa => 'Str'  );
  has 'connectorId' => (is => 'ro', isa => 'Str'  );
  has 'csObjectId' => (is => 'ro', isa => 'Str'  );
  has 'dn' => (is => 'ro', isa => 'Str'  );
  has 'errorCode' => (is => 'ro', isa => 'Str'  );
  has 'id' => (is => 'ro', isa => 'Str'  );
  has 'lastDirSyncTime' => (is => 'ro', isa => 'Str'  );
  has 'maxLimit' => (is => 'ro', isa => 'Str'  );
  has 'message' => (is => 'ro', isa => 'Str'  );
  has 'minLimit' => (is => 'ro', isa => 'Str'  );
  has 'modifiedAttributeValue' => (is => 'ro', isa => 'Str'  );
  has 'objectIdConflict' => (is => 'ro', isa => 'Str'  );
  has 'retryCount' => (is => 'ro', isa => 'Int'  );
  has 'runStepResultId' => (is => 'ro', isa => 'Str'  );
  has 'samAccountName' => (is => 'ro', isa => 'Str'  );
  has 'serverErrorDetail' => (is => 'ro', isa => 'Str'  );
  has 'timeFirstOccured' => (is => 'ro', isa => 'Str'  );
  has 'timeOccured' => (is => 'ro', isa => 'Str'  );
  has 'type' => (is => 'ro', isa => 'Str'  );
1;
