package Azure::Logic::EdifactEnvelopeSettings;
  use Moose;

  has 'applicationReferenceId' => (is => 'ro', isa => 'Str'  );
  has 'applyDelimiterStringAdvice' => (is => 'ro', isa => 'Bool'  );
  has 'communicationAgreementId' => (is => 'ro', isa => 'Str'  );
  has 'createGroupingSegments' => (is => 'ro', isa => 'Bool'  );
  has 'enableDefaultGroupHeaders' => (is => 'ro', isa => 'Bool'  );
  has 'functionalGroupId' => (is => 'ro', isa => 'Str'  );
  has 'groupApplicationPassword' => (is => 'ro', isa => 'Str'  );
  has 'groupApplicationReceiverId' => (is => 'ro', isa => 'Str'  );
  has 'groupApplicationReceiverQualifier' => (is => 'ro', isa => 'Str'  );
  has 'groupApplicationSenderId' => (is => 'ro', isa => 'Str'  );
  has 'groupApplicationSenderQualifier' => (is => 'ro', isa => 'Str'  );
  has 'groupAssociationAssignedCode' => (is => 'ro', isa => 'Str'  );
  has 'groupControlNumberLowerBound' => (is => 'ro', isa => 'Int'  );
  has 'groupControlNumberPrefix' => (is => 'ro', isa => 'Str'  );
  has 'groupControlNumberSuffix' => (is => 'ro', isa => 'Str'  );
  has 'groupControlNumberUpperBound' => (is => 'ro', isa => 'Int'  );
  has 'groupControllingAgencyCode' => (is => 'ro', isa => 'Str'  );
  has 'groupMessageRelease' => (is => 'ro', isa => 'Str'  );
  has 'groupMessageVersion' => (is => 'ro', isa => 'Str'  );
  has 'interchangeControlNumberLowerBound' => (is => 'ro', isa => 'Int'  );
  has 'interchangeControlNumberPrefix' => (is => 'ro', isa => 'Str'  );
  has 'interchangeControlNumberSuffix' => (is => 'ro', isa => 'Str'  );
  has 'interchangeControlNumberUpperBound' => (is => 'ro', isa => 'Int'  );
  has 'isTestInterchange' => (is => 'ro', isa => 'Bool'  );
  has 'overwriteExistingTransactionSetControlNumber' => (is => 'ro', isa => 'Bool'  );
  has 'processingPriorityCode' => (is => 'ro', isa => 'Str'  );
  has 'receiverInternalIdentification' => (is => 'ro', isa => 'Str'  );
  has 'receiverInternalSubIdentification' => (is => 'ro', isa => 'Str'  );
  has 'receiverReverseRoutingAddress' => (is => 'ro', isa => 'Str'  );
  has 'recipientReferencePasswordQualifier' => (is => 'ro', isa => 'Str'  );
  has 'recipientReferencePasswordValue' => (is => 'ro', isa => 'Str'  );
  has 'rolloverGroupControlNumber' => (is => 'ro', isa => 'Bool'  );
  has 'rolloverInterchangeControlNumber' => (is => 'ro', isa => 'Bool'  );
  has 'rolloverTransactionSetControlNumber' => (is => 'ro', isa => 'Bool'  );
  has 'senderInternalIdentification' => (is => 'ro', isa => 'Str'  );
  has 'senderInternalSubIdentification' => (is => 'ro', isa => 'Str'  );
  has 'senderReverseRoutingAddress' => (is => 'ro', isa => 'Str'  );
  has 'transactionSetControlNumberLowerBound' => (is => 'ro', isa => 'Int'  );
  has 'transactionSetControlNumberPrefix' => (is => 'ro', isa => 'Str'  );
  has 'transactionSetControlNumberSuffix' => (is => 'ro', isa => 'Str'  );
  has 'transactionSetControlNumberUpperBound' => (is => 'ro', isa => 'Int'  );
1;
