package Azure::ServiceFabricData::ApplicationUpgradeProgressInfo;
  use Moose;

  has 'CurrentUpgradeDomainProgress' => (is => 'ro', isa => 'Azure::ServiceFabricData::CurrentUpgradeDomainProgressInfo'  );
  has 'FailureReason' => (is => 'ro', isa => 'Str'  );
  has 'FailureTimestampUtc' => (is => 'ro', isa => 'Str'  );
  has 'Name' => (is => 'ro', isa => 'Str'  );
  has 'NextUpgradeDomain' => (is => 'ro', isa => 'Str'  );
  has 'RollingUpgradeMode' => (is => 'ro', isa => 'Str'  );
  has 'StartTimestampUtc' => (is => 'ro', isa => 'Str'  );
  has 'TargetApplicationTypeVersion' => (is => 'ro', isa => 'Str'  );
  has 'TypeName' => (is => 'ro', isa => 'Str'  );
  has 'UnhealthyEvaluations' => (is => 'ro', isa => 'ArrayRef[Azure::ServiceFabricData::HealthEvaluationWrapper]'  );
  has 'UpgradeDescription' => (is => 'ro', isa => 'Azure::ServiceFabricData::ApplicationUpgradeDescription'  );
  has 'UpgradeDomainDurationInMilliseconds' => (is => 'ro', isa => 'Str'  );
  has 'UpgradeDomainProgressAtFailure' => (is => 'ro', isa => 'Azure::ServiceFabricData::FailureUpgradeDomainProgressInfo'  );
  has 'UpgradeDomains' => (is => 'ro', isa => 'ArrayRef[Azure::ServiceFabricData::UpgradeDomainInfo]'  );
  has 'UpgradeDurationInMilliseconds' => (is => 'ro', isa => 'Str'  );
  has 'UpgradeState' => (is => 'ro', isa => 'Str'  );
  has 'UpgradeStatusDetails' => (is => 'ro', isa => 'Str'  );
1;
