package Azure::DevTestLab::LabVirtualMachineCreationParameter;
  use Moose;

  has 'location' => (is => 'ro', isa => 'Str'  );
  has 'name' => (is => 'ro', isa => 'Str'  );
  has 'tags' => (is => 'ro', isa => 'HashRef[Str]'  );
  has 'allowClaim' => (is => 'ro', isa => 'Bool'  );
  has 'artifactDeploymentStatus' => (is => 'ro', isa => 'Azure::DevTestLab::ArtifactDeploymentStatusProperties'  );
  has 'artifacts' => (is => 'ro', isa => 'ArrayRef[Azure::DevTestLab::ArtifactInstallProperties]'  );
  has 'bulkCreationParameters' => (is => 'ro', isa => 'Azure::DevTestLab::BulkCreationParameters'  );
  has 'computeId' => (is => 'ro', isa => 'Str'  );
  has 'createdByUser' => (is => 'ro', isa => 'Str'  );
  has 'createdByUserId' => (is => 'ro', isa => 'Str'  );
  has 'createdDate' => (is => 'ro', isa => 'Str'  );
  has 'customImageId' => (is => 'ro', isa => 'Str'  );
  has 'dataDiskParameters' => (is => 'ro', isa => 'ArrayRef[Azure::DevTestLab::DataDiskProperties]'  );
  has 'disallowPublicIpAddress' => (is => 'ro', isa => 'Bool'  );
  has 'environmentId' => (is => 'ro', isa => 'Str'  );
  has 'expirationDate' => (is => 'ro', isa => 'Str'  );
  has 'fqdn' => (is => 'ro', isa => 'Str'  );
  has 'galleryImageReference' => (is => 'ro', isa => 'Azure::DevTestLab::GalleryImageReference'  );
  has 'isAuthenticationWithSshKey' => (is => 'ro', isa => 'Bool'  );
  has 'labSubnetName' => (is => 'ro', isa => 'Str'  );
  has 'labVirtualNetworkId' => (is => 'ro', isa => 'Str'  );
  has 'lastKnownPowerState' => (is => 'ro', isa => 'Str'  );
  has 'networkInterface' => (is => 'ro', isa => 'Azure::DevTestLab::NetworkInterfaceProperties'  );
  has 'notes' => (is => 'ro', isa => 'Str'  );
  has 'osType' => (is => 'ro', isa => 'Str'  );
  has 'ownerObjectId' => (is => 'ro', isa => 'Str'  );
  has 'ownerUserPrincipalName' => (is => 'ro', isa => 'Str'  );
  has 'password' => (is => 'ro', isa => 'Str'  );
  has 'planId' => (is => 'ro', isa => 'Str'  );
  has 'scheduleParameters' => (is => 'ro', isa => 'ArrayRef[Azure::DevTestLab::ScheduleCreationParameter]'  );
  has 'size' => (is => 'ro', isa => 'Str'  );
  has 'sshKey' => (is => 'ro', isa => 'Str'  );
  has 'storageType' => (is => 'ro', isa => 'Str'  );
  has 'userName' => (is => 'ro', isa => 'Str'  );
  has 'virtualMachineCreationSource' => (is => 'ro', isa => 'Str'  );
1;
