package Azure::Migrate::AssessedMachineProperties;
  use Moose;

  has 'bootType' => (is => 'ro', isa => 'Str'  );
  has 'createdTimestamp' => (is => 'ro', isa => 'Str'  );
  has 'datacenterContainer' => (is => 'ro', isa => 'Str'  );
  has 'datacenterMachineId' => (is => 'ro', isa => 'Str'  );
  has 'datacenterManagementServer' => (is => 'ro', isa => 'Str'  );
  has 'datacenterManagementServerId' => (is => 'ro', isa => 'Str'  );
  has 'description' => (is => 'ro', isa => 'Str'  );
  has 'discoveredTimestamp' => (is => 'ro', isa => 'Str'  );
  has 'disks' => (is => 'ro', isa => 'HashRef[Azure::Migrate::AssessedDisk]'  );
  has 'displayName' => (is => 'ro', isa => 'Str'  );
  has 'groups' => (is => 'ro', isa => 'ArrayRef[Str]'  );
  has 'megabytesOfMemory' => (is => 'ro', isa => 'Num'  );
  has 'megabytesOfMemoryForRecommendedSize' => (is => 'ro', isa => 'Num'  );
  has 'monthlyBandwidthCost' => (is => 'ro', isa => 'Num'  );
  has 'monthlyComputeCostForRecommendedSize' => (is => 'ro', isa => 'Num'  );
  has 'monthlyStorageCost' => (is => 'ro', isa => 'Num'  );
  has 'networkAdapters' => (is => 'ro', isa => 'HashRef[Azure::Migrate::AssessedNetworkAdapter]'  );
  has 'numberOfCores' => (is => 'ro', isa => 'Int'  );
  has 'numberOfCoresForRecommendedSize' => (is => 'ro', isa => 'Int'  );
  has 'operatingSystem' => (is => 'ro', isa => 'Str'  );
  has 'percentageCoresUtilization' => (is => 'ro', isa => 'Num'  );
  has 'percentageCoresUtilizationDataPointsExpected' => (is => 'ro', isa => 'Int'  );
  has 'percentageCoresUtilizationDataPointsReceived' => (is => 'ro', isa => 'Int'  );
  has 'percentageMemoryUtilization' => (is => 'ro', isa => 'Num'  );
  has 'percentageMemoryUtilizationDataPointsExpected' => (is => 'ro', isa => 'Int'  );
  has 'percentageMemoryUtilizationDataPointsReceived' => (is => 'ro', isa => 'Int'  );
  has 'recommendedSize' => (is => 'ro', isa => 'Str'  );
  has 'suitability' => (is => 'ro', isa => 'Str'  );
  has 'suitabilityExplanation' => (is => 'ro', isa => 'Str'  );
  has 'updatedTimestamp' => (is => 'ro', isa => 'Str'  );
1;
