package Azure::Migrate::AssessmentProperties;
  use Moose;

  has 'azureHybridUseBenefit' => (is => 'ro', isa => 'Str'  );
  has 'azureLocation' => (is => 'ro', isa => 'Str'  );
  has 'azureOfferCode' => (is => 'ro', isa => 'Str'  );
  has 'azurePricingTier' => (is => 'ro', isa => 'Str'  );
  has 'azureStorageRedundancy' => (is => 'ro', isa => 'Str'  );
  has 'confidenceRatingInPercentage' => (is => 'ro', isa => 'Num'  );
  has 'createdTimestamp' => (is => 'ro', isa => 'Str'  );
  has 'currency' => (is => 'ro', isa => 'Str'  );
  has 'discountPercentage' => (is => 'ro', isa => 'Num'  );
  has 'monthlyBandwidthCost' => (is => 'ro', isa => 'Num'  );
  has 'monthlyComputeCost' => (is => 'ro', isa => 'Num'  );
  has 'monthlyStorageCost' => (is => 'ro', isa => 'Num'  );
  has 'numberOfMachines' => (is => 'ro', isa => 'Int'  );
  has 'percentile' => (is => 'ro', isa => 'Str'  );
  has 'pricesTimestamp' => (is => 'ro', isa => 'Str'  );
  has 'scalingFactor' => (is => 'ro', isa => 'Num'  );
  has 'sizingCriterion' => (is => 'ro', isa => 'Str'  );
  has 'stage' => (is => 'ro', isa => 'Str'  );
  has 'status' => (is => 'ro', isa => 'Str'  );
  has 'timeRange' => (is => 'ro', isa => 'Str'  );
  has 'updatedTimestamp' => (is => 'ro', isa => 'Str'  );
1;
