package Azure::ApiManagement::ReportRecordContract;
  use Moose;

  has 'apiId' => (is => 'ro', isa => 'Str'  );
  has 'apiRegion' => (is => 'ro', isa => 'Str'  );
  has 'apiTimeAvg' => (is => 'ro', isa => 'Num'  );
  has 'apiTimeMax' => (is => 'ro', isa => 'Num'  );
  has 'apiTimeMin' => (is => 'ro', isa => 'Num'  );
  has 'bandwidth' => (is => 'ro', isa => 'Int'  );
  has 'cacheHitCount' => (is => 'ro', isa => 'Int'  );
  has 'cacheMissCount' => (is => 'ro', isa => 'Int'  );
  has 'callCountBlocked' => (is => 'ro', isa => 'Int'  );
  has 'callCountFailed' => (is => 'ro', isa => 'Int'  );
  has 'callCountOther' => (is => 'ro', isa => 'Int'  );
  has 'callCountSuccess' => (is => 'ro', isa => 'Int'  );
  has 'callCountTotal' => (is => 'ro', isa => 'Int'  );
  has 'country' => (is => 'ro', isa => 'Str'  );
  has 'interval' => (is => 'ro', isa => 'Str'  );
  has 'name' => (is => 'ro', isa => 'Str'  );
  has 'operationId' => (is => 'ro', isa => 'Str'  );
  has 'productId' => (is => 'ro', isa => 'Str'  );
  has 'region' => (is => 'ro', isa => 'Str'  );
  has 'serviceTimeAvg' => (is => 'ro', isa => 'Num'  );
  has 'serviceTimeMax' => (is => 'ro', isa => 'Num'  );
  has 'serviceTimeMin' => (is => 'ro', isa => 'Num'  );
  has 'subscriptionId' => (is => 'ro', isa => 'Str'  );
  has 'timestamp' => (is => 'ro', isa => 'Str'  );
  has 'userId' => (is => 'ro', isa => 'Str'  );
  has 'zip' => (is => 'ro', isa => 'Str'  );
1;
